# 447 Project

In [55]:
import pandas as pd
import numpy as np

In [56]:
"""County Demographics - taken from https://opendata.maryland.gov/Demographic
/Choose-Maryland-Compare-Counties-Demographics/pa7d-u6hs"""

county_demographics = pd.read_csv("county_demographics.csv")

In [57]:
"""Socioeconomic Characteristics per County - taken from https://opendata.maryland.gov/Demographic
/Maryland-Jurisdictions-Socioeconomic-Characteristi/v67y-zu4n"""

county_socioeconomic = pd.read_csv("county_socioeconomic.csv")

In [58]:
"""County Vulnerability - taken from https://svi.cdc.gov"""

county_vulnerability = pd.read_csv("county_vulnerability.csv")

In [94]:
"""New Construction - taken from https://opendata.maryland.gov/Housing/
Maryland-Total-New-Parcels-For-Residential-Develop/6umw-84d2"""

county_development = pd.read_csv("county_development.csv")

(10, 27)

In [60]:
"""Find if vulnerability is correlated to less development"""

'Find if vulnerability is correlated to less development'

In [61]:
print(county_demographics.shape)
merge_name_demo = "County"

(24, 10)

In [62]:
print(county_socioeconomic.shape)
merge_name_socio = "Jurisdicions"

(24, 41)

In [63]:
print(county_vulnerability.shape)
merge_name_vuln = "COUNTY"

(24, 124)

In [93]:
county_development = county_development.sort_values("Year")
county_2012_data = county_development.loc[(county_development["Year"] >= 2012)]
county_12_16_avg = county_2012_data.groupby("Date created").mean()

"""Because data is from 2012 to 2016, the average data has been taken in this context"""

,Year,MARYLAND,Allegany County,Anne Arundel County,Baltimore City,Baltimore County,Calvert County,Caroline County,Carroll County,Cecil County,...,Kent County,Montgomery County,Prince George's County,Queen Anne's County,Somerset County,St. Mary's County,Talbot County,Washington County,Wicomico County,Worcester County
Date created,,,,,,,,,,,,,,,,,,,,,
5/15/2017,2013.5,9710.75,31.75,1455.0,185.25,772.25,221.25,23.25,330.0,164.75,...,35.25,1328.25,1345.25,181.0,21.0,373.25,43.75,191.5,110.0,91.25

In [66]:
dc_vulnerability = pd.read_csv("dc_vulnerability.csv")

In [67]:
county_combined_vulnerability = pd.concat([dc_vulnerability, county_vulnerability])

In [69]:
county_combined_vulnerability.head()

,FID,ST,STATE,ST_ABBR,COUNTY,FIPS,LOCATION,AREA_SQMI,E_TOTPOP,M_TOTPOP,...,F_CROWD,F_NOVEH,F_GROUPQ,F_THEME4,F_TOTAL,E_UNINSUR,M_UNINSUR,EP_UNINSUR,MP_UNINSUR,E_DAYPOP
0,0,11,DISTRICT OF COLUMBIA,DC,District of Columbia,11001,"District of Columbia, District of Columbia",61.145040,659009.0,0.0,...,-999.0,-999.0,-999.0,-999.0,-999.0,33419.0,1818.0,5.2,0.3,1134734.0
0,0,24,MARYLAND,MD,Anne Arundel,24003,"Anne Arundel County, Maryland",414.887094,559737.0,0.0,...,0.0,0.0,0.0,0.0,0.0,32248.0,1853.0,6.0,0.3,553075.0
1,1,24,MARYLAND,MD,Baltimore,24005,"Baltimore County, Maryland",598.361844,825666.0,0.0,...,0.0,0.0,0.0,0.0,0.0,60233.0,2259.0,7.4,0.3,821710.0
2,2,24,MARYLAND,MD,Calvert,24009,"Calvert County, Maryland",213.197148,90527.0,0.0,...,0.0,0.0,0.0,0.0,0.0,5327.0,744.0,6.0,0.8,67719.0
3,3,24,MARYLAND,MD,Carroll,24013,"Carroll County, Maryland",447.600142,167535.0,0.0,...,0.0,0.0,0.0,0.0,0.0,7249.0,711.0,4.4,0.4,137277.0

In [74]:
county_combined_vulnerability[["COUNTY", "E_MUNIT", "E_CROWD"]]

                  COUNTY   E_MUNIT  E_CROWD
0   District of Columbia  140304.0   9930.0
0           Anne Arundel   28410.0   3264.0
1              Baltimore   62724.0   5144.0
2                Calvert    1447.0    389.0
3                Carroll    3818.0    396.0
4                  Cecil    2477.0    583.0
5              Frederick   10028.0   1354.0
6                Harford   10081.0    985.0
7           Queen Anne's     380.0    253.0
8             Washington    5428.0   1065.0
9                Garrett     619.0     92.0
10            St. Mary's    2956.0    414.0
11                Talbot     579.0     62.0
12              Wicomico    4958.0    957.0
13               Charles    3560.0    650.0
14            Dorchester     985.0    125.0
15                Howard   19807.0   2135.0
16              Caroline     253.0    275.0
17                  Kent     569.0     63.0
18            Montgomery  102947.0  10973.0
19             Worcester   19814.0    216.0
20              Allegany    1835.0    254.0
21       Prince George's   75968.0  11812.0
22        Baltimore City   48374.0   4969.0
23              Somerset     767.0     80.0